- block:

  - name: Install Redis
    package:
      name: redis
      state: present
    retries: "{{ package_retries }}"
    register: result
    until: result is succeeded

  - name: Start Redis
    systemd:
      name: redis
      state: started
      enabled: yes
      daemon_reload: yes

  become: true
