- name: Upgrade installed packages
  package: name=* state=latest

- name: Install basic packages
  package: name={{ item }} state=present
  with_items:
      - bash-completion
      - fedora-easy-karma
      - htop
      - screen
      - tmux
      - tree
      - vim-enhanced

- name: Install packages requires to gather Pulp facts
  package: name={{ item }} state=present
  with_items:
      - git
      - rpm-build

- name: Gathering Pulp facts
  pulp_facts:
      devel_dir: "{{ pulp_devel_dir }}"
      venv_dir: "{{ pulp_venv_dir }}"
