- block:

  # Fedora 26 docker has a packaging problem where vim-enhanced will fail to
  # install if vim-minimal is out of date.
  - name: Try to install vim-enhanced
    package:
      name: vim-enhanced
      state: present
    register: result
    ignore_errors: yes
    retries: "{{ package_retries }}"
    until: result is succeeded

  - name: Upgrade vim-minimal if installing vim-enhanced failed
    package:
      name: vim-minimal
      state: latest
    when: result.failed
    tags:
      - skip_ansible_lint
    retries: "{{ package_retries }}"
    register: result
    until: result is succeeded

  - name: Install several useful packages
    package:
      name:
        - bash-completion
        - dnf-utils
        - dstat
        - fd-find
        - fedora-easy-karma
        - fpaste
        - fzf
        - htop
        - httpie
        - iotop
        - jnettop
        - jq
        - ncdu
        - python-django-bash-completion
        - python-ipdb
        - python-rpdb
        - python3-setuptools
        - redhat-lsb-core
        - ripgrep
        - screen
        - telnet
        - tmux
        - tree
        - wget
        - vim-enhanced
      state: present
    retries: "{{ package_retries }}"
    register: result
    until: result is succeeded

  become: true
