# This role could be made more idempotent by requesting that packages be
# "present," not "latest." The vim packaging issue could be solved with logic
# that says "if the current platform is Fedora and vim-enhanced isn't installed,
# let vim-minimal be latest."

# Fedora has a packaging problem where vim-enhanced will fail to install if
# vim-minimal is out of date.
- name: Upgrade vim-minimal
  package: name=vim-minimal state=latest

- name: Install optional useful packages
  package: name={{ item }} state=latest
  with_items:
      # System packages useful for most developers
      - bash-completion
      - fedora-easy-karma
      - htop
      - screen
      - tmux
      - tree
      - vim-enhanced
      - dstat
      - fpaste
      - iotop
      - jnettop
      - httpie
      - jq
      - python-django-bash-completion
      - redhat-lsb-core
      - telnet
      - yum-utils
      # Python packages useful for developers
      - python-ipdb
      - python3-setuptools
      - python-rpdb
