# This role could be made more idempotent by requesting that packages be
# "present," not "latest." The vim packaging issue could be solved with logic
# that says "if the current platform is Fedora and vim-enhanced isn't installed,
# let vim-minimal be latest."

# Fedora has a packaging problem where vim-enhanced will fail to install if
# vim-minimal is out of date.
- block:

  - name: Install latest version of vim-minimal
    package:
      name: vim-minimal
      state: latest
    tags:
      - skip_ansible_lint

  - name: Install latest version of several useful packages
    package:
      name:
        - bash-completion
        - dstat
        - fedora-easy-karma
        - fpaste
        - htop
        - httpie
        - iotop
        - jnettop
        - jq
        - python-django-bash-completion
        - python-ipdb
        - python-rpdb
        - python3-setuptools
        - redhat-lsb-core
        - screen
        - telnet
        - tmux
        - tree
        - vim-enhanced
        - yum-utils
      state: latest
    tags:
      - skip_ansible_lint

  become: true
