- block:

  # Fedora 26 docker has a packaging problem where vim-enhanced will fail to
  # install if vim-minimal is out of date.
  - name: Try to install vim-enhanced
    package:
      name: vim-enhanced
      state: present
    register: result

  - name: Upgrade vim-minimal if installing vim-enhanced failed
    package:
      name: vim-minimal
      state: latest
    when: result.failed
    tags:
      - skip_ansible_lint

  - name: Install several useful packages
    package:
      name:
        - bash-completion
        - dstat
        - fedora-easy-karma
        - fpaste
        - htop
        - httpie
        - iotop
        - jnettop
        - jq
        - python-django-bash-completion
        - python-ipdb
        - python-rpdb
        - python3-setuptools
        - redhat-lsb-core
        - screen
        - telnet
        - tmux
        - tree
        - vim-enhanced
        - yum-utils
      state: present

  become: true
