sudo: false
language: python
python:
  - 3.5
  - 3.6
install:
  - pip install ansible-lint
script:
  - ansible-playbook ansible/pulp-from-source.yml --syntax-check
  - ansible-lint ansible/pulp-from-source.yml
cache: pip
