- name: Install postgres packages
  package: name={{ item }} state=present
  with_items:
      - postgresql
      - postgresql-server
      # needed to install psycopg2 with python
      - postgresql-devel
      # needed by postgres-related tasks and other things
      # using python outside of a virtualenv
      - python3-psycopg2

- name: Set up postgres data dir
  command: postgresql-setup --initdb
  args:
      creates: /var/lib/pgsql/data/base

- name: Set up postgress access rules
  copy:
      src: pg_hba.conf
      dest: /var/lib/pgsql/data/pg_hba.conf
      owner: postgres
      group: postgres
      mode: 0600
  notify: restart postgresql

- name: Start and enable postgresql
  service: name=postgresql state=restarted enabled=yes

- name: Set up pulp DB user
  postgresql_user:
      name: pulp
      role_attr_flags: SUPERUSER,LOGIN

- name: Create pulp database
  postgresql_db:
      name: pulp
      owner: pulp
  register: pulp_postgres_db
