- block:

  - name: Install PostgreSQL
    package:
      name: postgresql-server
      state: present

  # Set environment variable to avoid encoding issues. See:
  # https://code.djangoproject.com/ticket/18710
  - name: Set up PostgreSQL data directory
    command: postgresql-setup {% if ansible_distribution == "Fedora" %}--{% endif %}initdb
    environment:
      PGSETUP_INITDB_OPTIONS: --encoding UTF-8
    args:
      creates: /var/lib/pgsql/data/base

  - name: Set up PostgreSQL access rules
    copy:
      src: pg_hba.conf
      dest: /var/lib/pgsql/data/pg_hba.conf
      owner: postgres
      group: postgres
      mode: 0600

  - name: Start and enable PostgreSQL
    systemd:
      name: postgresql
      state: started
      enabled: true

  - name: Install bindings required by the postgresql_* Ansible modules
    package:
      name: python{% if ansible_distribution == "Fedora" %}3{% endif %}-psycopg2
      state: present

  - name: Set up database user for Pulp
    postgresql_user:
      name: pulp
      role_attr_flags: SUPERUSER,LOGIN

  - name: Create database for Pulp
    postgresql_db:
      name: pulp
      owner: pulp

  become: true
