- block:

  - name: Install rabbitmq
    package:
      name: rabbitmq-server
      state: present

  - name: Start rabbitmq
    systemd:
      name: rabbitmq-server
      state: started
      enabled: yes
      daemon_reload: yes

  become: true
  when: use_rabbitmq

- block:

  - name: Install qpid
    package:
      name: qpid-cpp-server
      state: present

  - name: Start qpid
    systemd:
      name: qpidd
      state: started
      enabled: yes
      daemon_reload: yes

  become: true
  when: not use_rabbitmq
