- name: Install packages
  package: name={{ item }} state=present
  with_items:
    - rabbitmq-server

- name: Start and enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rabbitmq-server
