- name: Stop Pulp services
  systemd:
    name: '{{ item }}'
    state: stopped
  with_items: '{{ pulp_services | reverse | list }}'
  become: true
  # the services might not have been installed yet
  register: result
  failed_when: "result is failed and 'Could not find the requested service' not in result.msg"

- name: Run all migrations
  command: >
    {{ pulp_scl_enable_python3 }}
    {{ pulp_venv }}/bin/pulp-manager {{ item }}
  with_items:
    - reset_db --noinput
    - migrate auth --noinput
    - migrate --noinput
    - reset-admin-password --password admin
  become: true
  become_user: '{{ pulp_user }}'
  tags:
    - skip_ansible_lint


- name: Start Pulp services
  systemd:
    name: '{{ item }}'
    state: started
  with_items: '{{ pulp_services }}'
  become: true
  # the services might not have been installed yet
  register: result
  failed_when: "result is failed and 'Could not find the requested service' not in result.msg"
