---
# Install Pulp 3 from PyPi by using galaxy roles from requirements.yml
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    rabbitmq_config:
      - rabbit:
        - tcp_listeners:
          - '"localhost"': 5672
  pre_tasks:
    - name: Require minimal Python and Ansible versions
      assert:
        that:
          - "ansible_python_version|version_compare('3.5.0', operator='ge')"
          - "ansible_version.full|version_compare('2.2.0', operator='ge')"
        msg: >
          This role and those that depend on it require at least Python 3.5 and
          Ansible 2.2.
  roles:
    - pulp3
    - pulp3_db
    - rabbitmq
    - pulp3_systemd
