---
# Install Pulp 3 from PyPi by using galaxy roles from requirements.yml
- hosts: all
  become: true
  vars:
    rabbitmq_config:
      - rabbit:
        - tcp_listeners:
          - '"localhost"': 5672
  pre_tasks:
    - name: Require minimal Python and Ansible versions
      assert:
        that:
          - "ansible_python_version|version_compare('3.5.0', operator='ge')"
          - "ansible_version.full|version_compare('2.3.2', operator='ge')"
        msg: >
          This playbook requires Python 3.5+ and Ansible 2.3.2+. If your package
          manager ships an older version of Ansible, consider creating a
          virtualenv and installing Ansible with pip.
  roles:
    - pulp3
