---
# Install Pulp 3 from source.
#
# The resultant installation is designed to be useful for developers. It does
# things like install code in editable mode, install extra dependencies and
# install Bash aliases.
- hosts: pulp3_dev
  become: true
  become_method: sudo
  vars:
    supplement_bashrc: true
  roles:
    - vagrant
    - common
    - db
    - broker
    - lazy
    - dev
    - plugins
    - reset_db
    - systemd
    # - pulp_ca
    # - smash
    # - pulpproject
    - dev_tools
    # - release
    # - debug
