buildrequires:
- python-amqp
- python-kombu
- python-pymongo
- python-bson
copr-projects:
- '@pulp/2.10-nightlies'
external-deps:
- name: gofer
  release: 1%{?dist}
  version: 2.7.6
- name: python-amqp
  release: 2%{?dist}
  version: 1.4.9
- name: python-billiard
  release: 3%{?dist}
  version: 3.3.0.17
- name: python-kombu
  release: 6.pulp%{?dist}
  version: 3.0.33
- name: python-celery
  release: 2%{?dist}
  version: 3.1.11
- name: python-isodate
  release: 4.pulp%{?dist}
  version: 0.5.0
- name: python-pymongo
  release: 3%{?dist}
  version: 3.2.2
- name: python-mongoengine
  release: 3%{?dist}
  version: 0.10.5
- name: python-rhsm
  release: 2.pulp%{?dist}
  version: 1.8.0
- name: python-semantic_version
  release: 6%{?dist}
  version: 2.2.0
- name: python-qpid
  release: 11%{?dist}
  version: '0.18'
- name: saslwrapper
  release: 8%{?dist}
  version: '0.10'
platforms:
  el5:
  - epel-5-x86_64
  - epel-5-i386
  el6:
  - epel-6-x86_64
  - epel-6-i386
  el7:
  - epel-7-x86_64
  f23:
  - fedora-23-x86_64
  - fedora-23-i386
pulp-packages:
- name: pulp
  release: nightly
  treeish: master
  version: '2.10.0'
- name: pulp_docker
  release: nightly
  treeish: master
  version: '2.0.0'
- name: pulp_ostree
  release: nightly
  treeish: master
  version: '1.2.0'
- name: pulp_puppet
  release: nightly
  treeish: master
  version: '2.10.0'
- name: pulp_python
  release: nightly
  treeish: master
  version: '2.0.0'
- name: pulp_rpm
  release: nightly
  treeish: master
  version: '2.10.0'
- name: crane
  release: nightly
  treeish: master
  version: '2.0.0'
- name: nectar
  release: nightly
  treeish: master
  version: '1.6.0'
