- block:

  - name: Uninstall the Kombu we received from PyPI
    pip:
      name: kombu
      state: absent
      executable: '{{ pulp_scl_enable_python3 }}{{ pulp_venv }}/bin/pip'

  - name: Install kombu from source
    pip:
      name: git+https://github.com/bmbouter/kombu.git@624-convert-qpid-to-amqp-1.0#egg=kombu
      extra_args: '-e'
      executable: '{{ pulp_scl_enable_python3 }}{{ pulp_venv }}/bin/pip'

  become: true
  become_user: '{{ pulp_user }}'

- name: Install system packages proton needs
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - qpid-tools  # on system to provide 'qpid-stat' command
    - python-qpid-proton  # a required dependency of kombu
    - '{% if ansible_distribution == "RedHat" %}rh-python36-python-devel{% else %}python3-devel{% endif %}'  # allows for compilation during pip installs
    - gcc  # allows for compilation during pip installs
    - redhat-rpm-config  # dep for python-qpid-proton on Fedora cloud
  become: true

- name: Clone the patched qpid-tools
  git:
    repo: https://github.com/bmbouter/qpid-cpp
    dest: /tmp/qpid-cpp
    version: qpid-for-pulp

- name: Install qpid-tools from source
  command: '{{ pulp_scl_enable_python3 }}{{ pulp_venv }}/bin/python3 setup.py install'
  args:
    chdir: /tmp/qpid-cpp/management/python
  become: true

- name: Install python-qpid-proton from PyPI
  pip:
    name: python-qpid-proton
    executable: '{{ pulp_scl_enable_python3 }}{{ pulp_venv }}/bin/pip'
  become: true
  become_user: '{{ pulp_user }}'
